### ISSUE TITLE
Miswording in COVIDHunter-v2.swift

### ISSUE THREAD

**Issue by stevenyuser** [CMU-SAFARI/COVIDHunter#1]
Hi,

I was reading your preprint and code and noticed in [COVIDHunter-v2.swift](https://github.com/CMU-SAFARI/COVIDHunter/blob/main/src/COVIDHunter-v2.swift), that there is a slight miswording in the comment on line 177:
```
...
if (day%365 == 0) {
    dayInYear=0 // start new month (note approximates all months as having 30 days)
}...
```
It should probably be "// start new year". Just thought I'd bring up this quick fix!

Best Regards,
Steven Yu

P.S. It seems like the project is already mostly finished, but if there are still more things to do in this project, I would be happy to contribute to this project! I have experience in Swift (mostly writing iOS applications) and some experience in R.

**Comment by mealser** [comment]
Hi Steven,

Thanks for your message and for pinpointing the wrong comment.
I agree with you and I will fix it everywhere. 

I think there are always more improvements to be done and I am happy to discuss them with you early next year. Please drop me an email at alserm@ethz.ch

Best regards,
